In [7]:
#this is to try out the Data Processing and making all 5 steps of DS.
#1. Import the Data
#2. Missing Data
#3. Categorical Data
#4. Training / Test Data
#5. Feature Scaling 

In [8]:
#we need three Libs
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

In [9]:
np

<module 'numpy' from '/Users/apple/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'>

In [10]:
#Step 1: Import the Data Source
dataset = pd.read_csv("data-processing.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [19]:
#Step 2 : Missing Data - it is generic syntax and can be used for other projects as well.

#there are two variations on these 
# A) 
#salary Col 
dataset['Salary'].fillna(dataset['Salary'].groupby(dataset['Country']).transform('mean'),inplace=True)

#Age column
dataset['Age'].fillna(dataset['Age'].groupby(dataset['Country']).transform('mean'),inplace=True)

# B)
#dataset['Salary'].fillna(dataset['Salary'].groupby([dataset['Country'], dataset['Age']]).transform('mean'),inplace=True)

In [39]:
#ALL NaN filled with Averge salary depending on the country from above command and its basic command
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  68500.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  32.5  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [50]:
#Split the Data

x = dataset.iloc[:,:-1].values # all cols except last 
y = dataset.iloc[:,3].values # last col only    In the above Example its Purchsed Col As it is dependant Col

x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 68500.0],
       ['France', 35.0, 58000.0],
       ['Spain', 32.5, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [51]:
#Step 3: Data Encoding Categorical Data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [52]:
# always we need to do First Label Encoder then later OneHotEncoder

LabelEncoder_x=LabelEncoder()
x[:,0]=LabelEncoder_x.fit_transform(x[:,0])

In [53]:
#one hot encoder is dependant on Label Encoder  pass the Lable encoder to one hot encoder that is 'x' here 
OnehotEncoder=OneHotEncoder(categorical_features=[0])
x=OnehotEncoder.fit_transform(x).toarray()
x

array([[1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.70e+01, 4.80e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.00e+01, 5.40e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.85e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+01, 5.80e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.25e+01, 5.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.00e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.70e+01, 6.70e+04]])

In [49]:
#For Dependant we need to do a encodign 
LabelEncoder_y=LabelEncoder()
y=LabelEncoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [54]:
#Step 4 : Training the Data / Test Data

from sklearn.cross_validation import train_test_split

In [63]:
#random_state = 0 is used to set same result on a different machine/ in team evaluation

#x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [64]:
#Step 5 : Feature Scaling 

#in our example Y is already scaled during the encoder state no need to do for it 

from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)  # fit_transform is used to Feed the dat to ML (training) 
x_test=sc_x.transform(x_test) # transform is used to feed for test (our test data)
x_train,x_test

(array([[-0.63245553, -0.63245553,  1.15470054, -0.807236  , -0.99685157],
        [-0.63245553, -0.63245553,  1.15470054, -1.52999381, -1.32330588],
        [-0.63245553,  1.58113883, -0.8660254 ,  0.17834284,  0.34977248],
        [-0.63245553,  1.58113883, -0.8660254 ,  1.49244795,  1.53316937],
        [ 1.58113883, -0.63245553, -0.8660254 ,  1.22962693,  1.20671505],
        [ 1.58113883, -0.63245553, -0.8660254 , -0.47870972, -0.50717009],
        [-0.63245553, -0.63245553,  1.15470054, -0.08447819, -0.26232936]]),
 array([[-0.63245553,  1.58113883, -0.8660254 , -1.13576228, -0.83362441],
        [ 1.58113883, -0.63245553, -0.8660254 , -0.2158887 ,  0.22735211],
        [ 1.58113883, -0.63245553, -0.8660254 ,  0.70398488,  0.63542   ]]))