In [1]:
#stats functions

import numpy as np
from scipy import stats as st1
import statistics as stats2
from IPython.display import Image, display

In [2]:
numbers = np.arange(0,100)


In [17]:
type(numbers)
numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
#filter the number by using choice and random method 

sample1 = np.random.choice(numbers, size=10)

In [5]:
sample1

array([95, 28, 38, 80,  9,  5, 83, 71, 68,  1])

In [7]:
sample2 = np.random.choice(numbers, size=10)

In [8]:
#Mean of sample col vlaue 
Mean1 = np.mean(sample1)

In [9]:
Mean1

47.8

In [10]:
#Median of sample col vlaue 
Median1 = np.median(sample1)

In [11]:
Median1

53.0

In [16]:
#mode of a array
mode1 = stats.mode(sample1)

In [17]:
sample3 = [1,1,1,3,3,3,4,4,4,4,2,2,2]
mode2 = stats2.mode(sample3)

In [18]:
mode2

4

In [ ]:
#sept 8th Std and Variane Hands on 

In [20]:
sampleSD = np.random.choice(numbers, size=10)

In [21]:
sampleSD

array([83, 61, 71, 60,  1, 65, 46,  9, 52, 18])

In [24]:
#population variance 
PopulationVariance = stats2.pvariance(numbers)
PopulationVariance

833

In [26]:
#Sample variance 
VarianceSample = stats2.variance(sample1)
VarianceSample

1273

In [28]:
#population S.D
populationSD = stats2.pstdev(numbers)
populationSD

28.861739379323623

In [29]:
#sample S.D
sampleSD = stats2.stdev(sample1)
sampleSD

35.679125549822544

In [30]:
#percentile

#25% percentile means : 25% od data points less than the total data point
nums = np.array([10,20,30,40,50])
P25 = np.percentile(nums, 25)
P25

20.0

In [31]:
#range calulatinf using outlier 
Range = np.ptp(nums)
Range

40

In [ ]:
#Interquartile 
