In [ ]:
#Data processing is the 1st tstep of machine learning
#any dat from csv sql oledb or hadoop get in Dataframe using pandas
#if u want to join data from diferent sources then go for pd.merge else pd.concat(row below row data concat)
#data processing steps
#1.Merge all data and get in one variable so taht its easy for processing(IMPORT DATA)
#2.remove null,DUPLICATES OR FILL NULLS WITH SOME VALID DATA values(MISSINg DATA)
#3.CATEGORICAL DATA(converting text to numeric is callled categorical data)
#4.TRAINING SET/TEST SET
#5.FEATURE SCALING


In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [13]:
ds=pd.read_csv('Data.csv')
ds

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [44]:
ds['Salary'].fillna(ds['Salary'].groupby(ds['Country']).transform('mean'),inplace=True)
ds['Age'].fillna(ds['Age'].groupby(ds['Country']).transform('mean'),inplace=True)
ds

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  68500.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  32.5  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [18]:
# encoding Categorical data
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [50]:
x=ds.iloc[:,:-1].values # all cols except last
y=ds.iloc[:,3].values #last col only

In [51]:
LabelEncoder_x=LabelEncoder()
x[:,0]=LabelEncoder_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 68500.0],
       [0, 35.0, 58000.0],
       [2, 32.5, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [52]:
OnehotEncoder=OneHotEncoder(categorical_features=[0])
x=OnehotEncoder.fit_transform(x).toarray()
x

array([[1.00e+00, 0.00e+00, 0.00e+00, 4.40e+01, 7.20e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 2.70e+01, 4.80e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 3.00e+01, 5.40e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.80e+01, 6.10e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 4.00e+01, 6.85e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.50e+01, 5.80e+04],
       [0.00e+00, 0.00e+00, 1.00e+00, 3.25e+01, 5.20e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 4.80e+01, 7.90e+04],
       [0.00e+00, 1.00e+00, 0.00e+00, 5.00e+01, 8.30e+04],
       [1.00e+00, 0.00e+00, 0.00e+00, 3.70e+01, 6.70e+04]])

In [47]:
LabelEncoder_y=LabelEncoder()
y=LabelEncoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [36]:
#Split Data in traininga nd test ds
from sklearn.cross_validation import train_test_split

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [55]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)
x_train,x_test

(array([[ 0.8660254 ,  0.        , -0.8660254 , -0.0550749 ,  0.44897083],
        [-1.15470054,  0.        ,  1.15470054, -1.59717203, -1.41706417],
        [-1.15470054,  0.        ,  1.15470054, -0.74901861, -1.0242147 ],
        [ 0.8660254 ,  0.        , -0.8660254 ,  1.64123195,  1.62751925],
        [-1.15470054,  0.        ,  1.15470054,  0.09913482, -0.14030338],
        [ 0.8660254 ,  0.        , -0.8660254 ,  1.0243931 ,  0.94003267],
        [ 0.8660254 ,  0.        , -0.8660254 , -0.36349432, -0.43494049]]),
 array([[-1.15470054,  1.        , -0.8660254 , -1.13454289, -0.82778996],
        [-1.15470054,  1.        , -0.8660254 ,  1.94965138,  2.02036872],
        [-1.15470054,  1.        , -0.8660254 ,  0.40755424,  0.59628938]]))